from typing import Any, Protocol, Callable, TypeVar, Generic

class Expr: ...
class LazyFrame: ...
class DataFrame: ...

def col(name: str) -> Expr: ...

def concat_str(*args: Any, **kwargs: Any) -> Expr: ...

def Series(*args: Any, **kwargs: Any) -> Any: ...